services:
  - type: web
    name: signups4fastcash
    env: node
    plan: free
    region: oregon
    domains:
      - signups4fastcash.com
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_URL
        value: https://signups4fastcash.com
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: signups4fastcash-db
          property: connectionString
      - key: ADMIN_PASSCODE
        sync: false
      - key: CPX_APP_ID
        value: "36089"
      - key: CPX_SECURE_HASH
        sync: false

databases:
  - name: signups4fastcash-db
    plan: free
